name: Validate and test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

jobs:
  check-code-style:
    name: Checks
    runs-on: ubuntu-22.04
    if: github.repository == 'akka/akka-diagnostics'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Set up JDK 11
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.11.0

      - name: Code style check, compilation and binary-compatibility check
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt scalafmtCheckAll scalafmtSbtCheck headerCheck +Test/compile
          
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    if: github.repository == 'akka/akka-diagnostics'
    strategy:
      fail-fast: false
      matrix:
        include:
          - { jdkVersion: "1.11.0", jvmName: "temurin:1.11.0" }
          - { jdkVersion: "1.17.0", jvmName: "temurin:1.17.0" }
          - { jdkVersion: "1.21.0", jvmName: "temurin:1.21" }

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Set up JDK ${{ matrix.jdkVersion }}
        uses: coursier/setup-action@v1.3.4
        with:
          jvm: ${{ matrix.jvmName }}
          # FIXME default index not giving us access to JDK 21 (yet)
          jvm-index: https://raw.githubusercontent.com/coursier/jvm-index/32d659500e6c65efb9eee91718a0fb0e797ad4ee/index.json


      - name: sbt test
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt test

  check-docs:
    name: Check Docs
    runs-on: ubuntu-22.04
    if: github.repository == 'akka/akka-diagnostics'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Set up JDK 17
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.17.0

      - name: Create all API docs for artifacts/website and all reference docs
        run: sbt "unidoc; docs/paradox"
