name: Validate and test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [v.*]

permissions:
  contents: read

jobs:
  check-code-style:
    name: Checks
    runs-on: Akka-Default
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Akka resolver setup
        uses: akka/github-actions-scripts/setup_global_resolver@main

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up JDK 11
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.11.0

      - name: Code style check, compilation and binary-compatibility check
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt scalafmtCheckAll scalafmtSbtCheck headerCheck +Test/compile

      - name: Artifact BOM validation
        uses: akka/github-actions-scripts/artifact_bom_validation@main

  test:
    name: Run tests
    runs-on: Akka-Default
    if: github.event.repository.fork == false
    strategy:
      fail-fast: false
      matrix:
        include:
          - { jdkVersion: "1.11.0", jvmName: "temurin:1.11.0" }
          - { jdkVersion: "1.17.0", jvmName: "temurin:1.17.0" }
          - { jdkVersion: "1.21.0", jvmName: "temurin:1.21" }
          - { jdkVersion: "1.25.0", jvmName: "temurin:1.25" }

    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout Global Scripts
        uses: actions/checkout@v6
        with:
          repository: akka/github-actions-scripts
          path: scripts
          fetch-depth: 0

      - name: Setup global resolver
        run: |
          chmod +x ./scripts/setup_global_resolver.sh
          ./scripts/setup_global_resolver.sh

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up JDK ${{ matrix.jdkVersion }}
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: ${{ matrix.jvmName }}

      - name: sbt test
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt test
